import { ThemeProvider } from "@/app/_components/theme-provider";
import { Locale } from "@/app/_types/locale";
import { getDirection } from "@/app/_utils/getDirection";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ReactNode } from "react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: ReactNode;
  params: Promise<{ lang: Locale }>;
};

const Layout = async ({ children, params }: LayoutProps) => {
  const { lang } = await params;
  const dir = getDirection(lang);

  return (
    <html lang={lang} dir={dir}>
      <body className={poppins.variable}>
        <ThemeProvider dir={dir}>{children}</ThemeProvider>
      </body>
    </html>
  );
};

export { metadata };
export default Layout;
