const d = {
  barcode: "بارکد",
  defaultLoading: "در حال فراخوانی",
  downloadQrCode: "دانلود کیو آر کد",
  publicPageLink: "لینک صفحه عمومی",
  copied: "کپی شد",
  copyLink: "کپی لینک",
  view: "مشاهده",
  viewPublicPage: "مشاهده صفحه عمومی",
  gender: "جنسیت",
  male: "مرد",
  female: "زن",
  employeeInformation: "اطلاعات کارمند",
  specifications: "مشخصات",
  connectivity: "درگاه‌های ارتباطی",
  print: "چاپ",
  emailAddress: "آدرس ایمیل",
  kiosk: "کیوسک",
  supportService: "خدمت پشتیبانی",
  user: "کاربر",
  fullName: "نام کامل",
  email: "ایمیل",
  password: "پسورد",
  role: "نقش",
  createUser: "ایجاد کاربر",
  createEmployee: "ایجاد کارمند",
  editEmployee: "ویرایش کارمند",
  submit: "ثبت",
  errorValidationTitle: "لطفا ورودی های خود را بررسی کنید",
  create: "ایجاد",
  edit: "ویرایش",
  signIn: "ورود",
  editUser: "ویرایش کاربر",
  required: "اجباری",
  invalid: "نامعتبر",
  passwordValidation:
    "حداقل هشت کاراکتر، حداقل یک حرف بزرگ، حداقل یک حرف کوچک، حداقل یک کاراکتر خاص، حداقل یک عدد",
  minimumOneUpperCaseLetter: "حداقل یک حرف بزرگ",
  minimumOneLowerCaseLetter: "حداقل یک حرف کوچک",
  minimumOneDigit: "حداقل یک عدد",
  minimumOneSpecialCharacter: "حداقل یک کاراکتر خاص",
  minimum: "حداقل",
  character: "کاراکتر",
  firstName: "نام",
  lastName: "نام خانوادگی",
  maximum: "حداکثر",
  invalidEmail: "ایمیل نامعتبر",
  minEightCharacters: "حداقل هشت کاراکتر",
  imageSource: "تصویر",
  phoneNumber: "شماره همراه",
  position: "سمت",
  personnelCode: "کد پرسنلی",
  jobDescription: "شرح وظایف سازمانی",
  hireDate: "تاریخ استخدام",
  employmentStatus: "وضعیت کاری",
  endOfCooperation: "پایان همکاری",
  active: "فعال",
  inactive: "غیر فعال",
  onLeave: "در حال ترک",
  employmentType: "نوع استخدام",
  contract: "قراردادی",
  official: "رسمی",
  unofficial: "غیر رسمی",
  employee: "کارمند",
  image: "تصویر",
  auto: "خودکار",
  dark: "تاریک",
  light: "روشن",
  groupDelete: "حذف گروهی",
  description: "توضیحات",
  permissions: "دسترسی ها",
  notFound: "یافت نشد",
  notAuthorized: "عدم مجوز دسترسی",
  supportServices: "خدمات پشتیبانی",
  title: "عنوان خدمت پشتیبانی",
  remoteSupportsCount: "تعداد پشتیبانی تلفنی/از راه دور",
  supportHours: "ساعات پاسخگویی",
  supportDays: "روزهای پاسخگویی",
  onSiteSupportsCount: "تعداد پشتیبانی حضوری",
  phoneSupporter: "پشتیبان در اختیار (تلفنی)",
  partTimeSupporter: "پشتیبان در اختیار (پاره وقت)",
  fullTimeSupporter: "پشتیبان در اختیار (تمام وقت)",
  remoteReinstallCount: "دفعات نصب مجدد از راه دور",
  onSiteInstallCount: "تعداد نصب حضوری نرم افزار",
  retraining: "آموزش مجدد نرم افزار/سخت افزار",
  replacementPrinter: "پرینتر جایگزین",
  replacementTablet: "تبلت جایگزین",
  replacementAllInOne: "آل این وان جایگزین",
  replacementKiosk: "کیوسک جایگزین",
  createSupportService: "ایجاد خدمت پشتیبانی جدید",
  editSupportService: "ویرایش خدمت پشتیبانی",

  // messages
  userCreatedSuccessfully: "کاربر با موفقیت ایجاد شد",
  userEditedSuccessfully: "کاربر با موفقیت ویرایش شد",
  userDeletedSuccessfully: "کاربر با موفقیت حذف شد",
  usersDeletedSuccessfully: "کاربران با موفقیت حذف شدند",
  loggedInSuccessfully: "با موفقیت وارد شدید",
  createProduct: "ایجاد محصول",
  editProduct: "ویرایش محصولات",
  usersManagement: "مدیریت کاربران",
  users: "کاربران",
  addUser: "افزودن کاربر",
  employeesManagement: "مدیریت کارمندان",
  employees: "کارمندان",
  mediaManagement: "مدیریت رسانه",
  roles: "نقش ها",
  addRole: "افزودن نقش",
  productsManagement: "مدیریت محصولات",
  kiosks: "کیوسک ها",
  addKiosk: "addKiosk",
  createKiosk: "ایجاد کیوسک",
  createRole: "ایجاد نقش",
  editRole: "ویرایش نقش",
  editKiosk: "ویرایش کیوسک",
  employeeCreatedSuccessfully: "کارمند با موفقیت ایجاد شد",
  employeeEditedSuccessfully: "کارمند با موفقیت ویرایش شد",
  employeeDeletedSuccessfully: "کارمند با موفقیت حذف شد",
  employeesDeletedSuccessfully: "کارمندان با موفقیت حذف شدند",

  // old

  overwriteDatabase: "رونویسی دیتابیس",
  addEmployee: "افزودن کارمند",
  uploadFile: "آپلود فایل",
  advanced: "پیشرفته",
  name: "نام",
  download: "دانلود",
  backup: "پشتیبان گیری",
  storage: "حافظه",
  dimensions: "ابعاد",
  close: "بستن",
  weightKg: "وزن",
  property: "ویژگی",
  model: "مدل",
  share: "اشتراک گذاری",
  cpuModel: "مدل سی پی یو",
  displayModel: "مدل صفحه نمایش",
  toman: "تومان",
  bodyMaterial: "جنس بدنه",
  weight: "وزن",
  length: "طول",
  width: "عمق",
  height: "ارتفاع",
  os: "سیستم عامل",
  display: "صفحه نمایش",
  touchTechnology: "تکنولوژی لمسی",
  cpu: "پردازنده",
  storageSize: "حافظه",
  storageType: "نوع حافظه",
  storageExpandable: "قابلیت ارتقا حافظه",
  ram: "رم",
  ramExpandable: "قابلیت ارتقا رم",
  includesSpeaker: "اسپیکر دارد",
  ports: "پورت ها",
  additionalFeatures: "قابلیت افزودن امکانات شخصی سازی",
  price: "قیمت",
  modelName: "نام مدل",
  megaByte: "مگابایت",
  size: "حجم",
  file: "فایل",
  label: "عنوان",
  selectFile: "انتخاب فایل",
  media: "رسانه",
  overview: "در یک نگاه",
  products: "محصولات",
  general: "عمومی",
  dashboard: "پنل کاربری",
  management: "مدیریت",
  list: "لیست",
  delete: "حذف",
  basicUser: "کاربر پایه",
  superAdmin: "سوپر ادمین",
  noRole: "بدون سمت",
  signInToDashboard: "ورود به پنل کاربری",
  signOut: "خروج",
  confirmOperation: "تایید عملیات",
  doYouConfirmOperation: "آیا عملیات را تایید می کنید؟",
  cancel: "لغو",
  confirm: "تایید",
  allInOneModel: "مدل آل این وان",
  peripheralEquipment: "تجهیزات جانبی",
  printerModel: "مدل پرینتر",
  printerSerial: "سریال پرینتر",
  barcodeScanner: "بارکد اسکنر",
  networkSwitch: "سوییچ شبکه",
  flatBed: "فلت بد",
  secondMonitor: "مانیتور دوم",
  motherboard: "مادربرد",
  accessories: "متعلقات",
  signedOutSuccessfully: "با موفقیت خارج شدید",
  noFileSelected: "فایلی انتخاب نشده است",
  maximumFileUploadSize: "حداکثر حجم فایل 5 مگابایت",
  notSupportedFormat: "فرمت فایل غیر مجاز است",
  fileUploadedSuccessfully: "فایل با موفقیت آپلود شد",
  fileIsDuplicated: "فایل تکراری است",
  fileRemovedSuccessfully: "فایل با موفقیت حذف شد",
  filesRemovedSuccessfully: "فایل ها با موفقیت حذف شدند",
  kioskCreateSuccessfully: "کیوسک با موفقیت ایجاد شد",
  kioskEditedSuccessfully: "کیوسک با موفقیت ویرایش شد",
  kioskDeletedSuccessfully: "کیوسک با موفقیت حذف شد",
  supportServiceCreateSuccessfully: "خدمت پشتیبانی با موفقیت ایجاد شد",
  supportServiceEditedSuccessfully: "خدمت پشتیبانی با موفقیت ویرایش شد",
  supportServiceDeletedSuccessfully: "خدمت پشتیبانی با موفقیت حذف شد",
  supportServicesDeletedSuccessfully: "خدمات پشتیبانی با موفقیت حذف شدند",
  roleCreateSuccessfully: "نقش با موفقیت ایجاد شد",
  roleEditedSuccessfully: "نقش با موفقیت ویرایش شد",
  roleDeletedSuccessfully: "نقش با موفقیت حذف شد",
  rolesDeletedSuccessfully: "نقش ها با موفقیت حذف شدند",
  backedUpSuccessfully: "پشتیبان گیری با موفقیت انجام شد",
  backupUpImportedSuccessfully: "فایل پشتیبان با موفقیت بارگذاری شد",
  settings: "تنظیمات",
} as const;

export { d };
